/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as LobbyIdRouteRouteImport } from './routes/$lobbyId/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LobbyIdWaitingRouteImport } from './routes/$lobbyId/waiting'
import { Route as LobbyIdPlayingRouteImport } from './routes/$lobbyId/playing'
import { Route as LobbyIdFinishedRouteImport } from './routes/$lobbyId/finished'

const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport
} as any)
const LobbyIdRouteRoute = LobbyIdRouteRouteImport.update({
  id: '/$lobbyId',
  path: '/$lobbyId',
  getParentRoute: () => rootRouteImport
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport
} as any)
const LobbyIdWaitingRoute = LobbyIdWaitingRouteImport.update({
  id: '/waiting',
  path: '/waiting',
  getParentRoute: () => LobbyIdRouteRoute
} as any)
const LobbyIdPlayingRoute = LobbyIdPlayingRouteImport.update({
  id: '/playing',
  path: '/playing',
  getParentRoute: () => LobbyIdRouteRoute
} as any)
const LobbyIdFinishedRoute = LobbyIdFinishedRouteImport.update({
  id: '/finished',
  path: '/finished',
  getParentRoute: () => LobbyIdRouteRoute
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lobbyId': typeof LobbyIdRouteRouteWithChildren
  '/debug': typeof DebugRoute
  '/$lobbyId/finished': typeof LobbyIdFinishedRoute
  '/$lobbyId/playing': typeof LobbyIdPlayingRoute
  '/$lobbyId/waiting': typeof LobbyIdWaitingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lobbyId': typeof LobbyIdRouteRouteWithChildren
  '/debug': typeof DebugRoute
  '/$lobbyId/finished': typeof LobbyIdFinishedRoute
  '/$lobbyId/playing': typeof LobbyIdPlayingRoute
  '/$lobbyId/waiting': typeof LobbyIdWaitingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lobbyId': typeof LobbyIdRouteRouteWithChildren
  '/debug': typeof DebugRoute
  '/$lobbyId/finished': typeof LobbyIdFinishedRoute
  '/$lobbyId/playing': typeof LobbyIdPlayingRoute
  '/$lobbyId/waiting': typeof LobbyIdWaitingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lobbyId'
    | '/debug'
    | '/$lobbyId/finished'
    | '/$lobbyId/playing'
    | '/$lobbyId/waiting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lobbyId'
    | '/debug'
    | '/$lobbyId/finished'
    | '/$lobbyId/playing'
    | '/$lobbyId/waiting'
  id:
    | '__root__'
    | '/'
    | '/$lobbyId'
    | '/debug'
    | '/$lobbyId/finished'
    | '/$lobbyId/playing'
    | '/$lobbyId/waiting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LobbyIdRouteRoute: typeof LobbyIdRouteRouteWithChildren
  DebugRoute: typeof DebugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lobbyId': {
      id: '/$lobbyId'
      path: '/$lobbyId'
      fullPath: '/$lobbyId'
      preLoaderRoute: typeof LobbyIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lobbyId/waiting': {
      id: '/$lobbyId/waiting'
      path: '/waiting'
      fullPath: '/$lobbyId/waiting'
      preLoaderRoute: typeof LobbyIdWaitingRouteImport
      parentRoute: typeof LobbyIdRouteRoute
    }
    '/$lobbyId/playing': {
      id: '/$lobbyId/playing'
      path: '/playing'
      fullPath: '/$lobbyId/playing'
      preLoaderRoute: typeof LobbyIdPlayingRouteImport
      parentRoute: typeof LobbyIdRouteRoute
    }
    '/$lobbyId/finished': {
      id: '/$lobbyId/finished'
      path: '/finished'
      fullPath: '/$lobbyId/finished'
      preLoaderRoute: typeof LobbyIdFinishedRouteImport
      parentRoute: typeof LobbyIdRouteRoute
    }
  }
}

interface LobbyIdRouteRouteChildren {
  LobbyIdFinishedRoute: typeof LobbyIdFinishedRoute
  LobbyIdPlayingRoute: typeof LobbyIdPlayingRoute
  LobbyIdWaitingRoute: typeof LobbyIdWaitingRoute
}

const LobbyIdRouteRouteChildren: LobbyIdRouteRouteChildren = {
  LobbyIdFinishedRoute: LobbyIdFinishedRoute,
  LobbyIdPlayingRoute: LobbyIdPlayingRoute,
  LobbyIdWaitingRoute: LobbyIdWaitingRoute
}

const LobbyIdRouteRouteWithChildren = LobbyIdRouteRoute._addFileChildren(
  LobbyIdRouteRouteChildren
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LobbyIdRouteRoute: LobbyIdRouteRouteWithChildren,
  DebugRoute: DebugRoute
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
